### ISSUE TITLE
Need more detail to build on MacOSX and build multiple architechture to combine lib

### ISSUE THREAD

**Issue by bapzangbo** [steakknife/libtorrent-ios#1]
Hi @steakknife , and sorry about my bad English

 i search how to build libtorrent for ios and look for your git. but seem to you git similar with the git of libtorrent. Can you tell more detail about how to build lib with boost or with autotools of libtorrent. specially, how to build for mutiple architechture such as Arm, i386, x68_64.and how to combine this to Universal library, that can be use for simulator iphone. 
Wish your answer, thanks for your attenttion ^^.

**Comment by steakknife** [comment]
This is someone else's hacky fork for iOS compatibility.  If your target is OSX, you should be using libtorrent proper.
